### ISSUE TITLE
Sketch 3.4.2: day-player creates a 0px x 0px white image 

### ISSUE THREAD

**Issue by jcloutz** [tylergaw/day-player#29] opened 2015-11-26 00:49 UTC
I recently downloaded this plugin and it seems to have a problem with Sketch 3.4.2. Whenever I try to place an image it creates a 0px by 0px solid white image. Has anyone else had this problem?

**Comment by jbishop228** [comment] 2015-11-30 22:25
Yeah getting the same issue with the latest Sketch update (3.4.2). A lot of plugins have gone awry since the update it seems.

**Comment by daneclarkcollins** [comment] 2015-12-14 18:30
Same here.

**Comment by akhalizev** [comment] 2015-12-16 11:26
For me too.

**Comment by Hiswe** [comment] 2015-12-24 03:42
Same issue on 3.4.4

**Comment by LukePettway** [comment] 2015-12-24 15:06
Seems like a lot of plugins are breaking with the new update.

**Comment by OssamaZ** [comment] 2015-12-31 14:23
The problem is in the "createAndPlaceImg" function, the layer.setRawImage_convertColourspace_collection rises an exception.

**Comment by tylergaw** [comment] 2016-01-13 07:07
Just got PR #30 merged in to fix this. Will be pushing out a new release shortly.

**Closed** 2016-01-13 07:07 UTC

**Comment by tylergaw** [comment] 2016-01-13 07:18
@jcloutz Thanks for the report, sorry about the slow response, been a busy couple months. From what I can tell, I have this fixed in the latest release https://github.com/tylergaw/day-player/releases/tag/v2.1.0

**Comment by jcloutz** [comment] 2016-01-14 03:57
Awesome, thank you @tylergaw.
